// <auto-generated />
using ChiTrung.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ChiTrung.Infra.Data.Migrations
{
    [DbContext(typeof(TigersContext))]
    partial class TigersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChiTrung.Domain.Models.GameEvents", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Event");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnName("GameID")
                        .HasMaxLength(128);

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnName("MemberID")
                        .HasMaxLength(128);

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnName("MerchantID")
                        .HasMaxLength(128);

                    b.Property<Guid>("TransactionId")
                        .HasColumnName("TransactionID");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("MerchantId", "MemberId", "GameId")
                        .IsUnique();

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("ChiTrung.Domain.Models.GameState", b =>
                {
                    b.Property<string>("MerchantId")
                        .HasColumnName("MerchantID")
                        .HasMaxLength(128);

                    b.Property<string>("MemberId")
                        .HasColumnName("MemberID")
                        .HasMaxLength(128);

                    b.Property<string>("GameId")
                        .HasColumnName("GameID")
                        .HasMaxLength(128);

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Payload");

                    b.HasKey("MerchantId", "MemberId", "GameId");

                    b.ToTable("GameState");
                });

            modelBuilder.Entity("ChiTrung.Domain.Models.Users", b =>
                {
                    b.Property<string>("MerchantId")
                        .HasColumnName("MerchantID")
                        .HasMaxLength(128);

                    b.Property<string>("MemberId")
                        .HasColumnName("MemberID")
                        .HasMaxLength(128);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("MerchantId", "MemberId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
